execute @e[tag=track] ~ ~ ~ execute @a[r=65,rm=0] ~ ~ ~  function ingame/chunks/4
execute @e[tag=track] ~ ~ ~ execute @a[r=129,rm=65] ~ ~ ~ function ingame/chunks/8
execute @e[tag=track] ~ ~ ~ execute @a[r=193,rm=129] ~ ~ ~  function ingame/chunks/12
execute @e[tag=track] ~ ~ ~ execute @a[r=257,rm=193] ~ ~ ~ function ingame/chunks/16
execute @e[tag=track] ~ ~ ~ execute @a[r=321,rm=257] ~ ~ ~  function ingame/chunks/20
execute @e[tag=track] ~ ~ ~ execute @a[r=385,rm=321] ~ ~ ~ function ingame/chunks/24
execute @e[tag=track] ~ ~ ~ execute @a[r=449,rm=385] ~ ~ ~  function ingame/chunks/28
execute @e[tag=track] ~ ~ ~ execute @a[r=513,rm=449] ~ ~ ~ function ingame/chunks/32
execute @e[tag=track] ~ ~ ~ execute @a[r=577,rm=513] ~ ~ ~  function ingame/chunks/36
execute @e[tag=track] ~ ~ ~ execute @a[r=641,rm=577] ~ ~ ~ function ingame/chunks/40
execute @e[tag=track] ~ ~ ~ execute @a[r=705,rm=641] ~ ~ ~  function ingame/chunks/44
execute @e[tag=track] ~ ~ ~ execute @a[r=769,rm=705] ~ ~ ~ function ingame/chunks/48