#function detecting 0-4 chunks / 0-64 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=1,rm=0] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 0m
execute @e[tag=track] ~ ~ ~ execute @a[r=2,rm=1] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1m
execute @e[tag=track] ~ ~ ~ execute @a[r=3,rm=2] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 2m
execute @e[tag=track] ~ ~ ~ execute @a[r=4,rm=3] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 3m
execute @e[tag=track] ~ ~ ~ execute @a[r=5,rm=4] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 4m
execute @e[tag=track] ~ ~ ~ execute @a[r=6,rm=5] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 5m
execute @e[tag=track] ~ ~ ~ execute @a[r=7,rm=6] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 6m
execute @e[tag=track] ~ ~ ~ execute @a[r=8,rm=7] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 7m
execute @e[tag=track] ~ ~ ~ execute @a[r=9,rm=8] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 8m
execute @e[tag=track] ~ ~ ~ execute @a[r=10,rm=9] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 9m
execute @e[tag=track] ~ ~ ~ execute @a[r=11,rm=10] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 10m
execute @e[tag=track] ~ ~ ~ execute @a[r=12,rm=11] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 11m
execute @e[tag=track] ~ ~ ~ execute @a[r=13,rm=12] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 12m
execute @e[tag=track] ~ ~ ~ execute @a[r=14,rm=13] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 13m
execute @e[tag=track] ~ ~ ~ execute @a[r=15,rm=14] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 14m
execute @e[tag=track] ~ ~ ~ execute @a[r=16,rm=15] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 15m
execute @e[tag=track] ~ ~ ~ execute @a[r=17,rm=16] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 16m
execute @e[tag=track] ~ ~ ~ execute @a[r=18,rm=17] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 17m
execute @e[tag=track] ~ ~ ~ execute @a[r=19,rm=18] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 18m
execute @e[tag=track] ~ ~ ~ execute @a[r=20,rm=19] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 19m
execute @e[tag=track] ~ ~ ~ execute @a[r=21,rm=20] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 20m
execute @e[tag=track] ~ ~ ~ execute @a[r=22,rm=21] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 21m
execute @e[tag=track] ~ ~ ~ execute @a[r=23,rm=22] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 22m
execute @e[tag=track] ~ ~ ~ execute @a[r=24,rm=23] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 23m
execute @e[tag=track] ~ ~ ~ execute @a[r=25,rm=24] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 24m
execute @e[tag=track] ~ ~ ~ execute @a[r=26,rm=25] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 25m
execute @e[tag=track] ~ ~ ~ execute @a[r=27,rm=26] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 26m
execute @e[tag=track] ~ ~ ~ execute @a[r=28,rm=27] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 27m
execute @e[tag=track] ~ ~ ~ execute @a[r=29,rm=28] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 28m
execute @e[tag=track] ~ ~ ~ execute @a[r=30,rm=29] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 29m
execute @e[tag=track] ~ ~ ~ execute @a[r=31,rm=30] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 30m
execute @e[tag=track] ~ ~ ~ execute @a[r=32,rm=31] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 31m
execute @e[tag=track] ~ ~ ~ execute @a[r=33,rm=32] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 32m
execute @e[tag=track] ~ ~ ~ execute @a[r=34,rm=33] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 33m
execute @e[tag=track] ~ ~ ~ execute @a[r=35,rm=34] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 34m
execute @e[tag=track] ~ ~ ~ execute @a[r=36,rm=35] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 35m
execute @e[tag=track] ~ ~ ~ execute @a[r=37,rm=36] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 36m
execute @e[tag=track] ~ ~ ~ execute @a[r=38,rm=37] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 37m
execute @e[tag=track] ~ ~ ~ execute @a[r=39,rm=38] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 38m
execute @e[tag=track] ~ ~ ~ execute @a[r=40,rm=39] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 39m
execute @e[tag=track] ~ ~ ~ execute @a[r=41,rm=40] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 40m
execute @e[tag=track] ~ ~ ~ execute @a[r=42,rm=41] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 41m
execute @e[tag=track] ~ ~ ~ execute @a[r=43,rm=42] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 42m
execute @e[tag=track] ~ ~ ~ execute @a[r=44,rm=43] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 43m
execute @e[tag=track] ~ ~ ~ execute @a[r=45,rm=44] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 44m
execute @e[tag=track] ~ ~ ~ execute @a[r=46,rm=45] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 45m
execute @e[tag=track] ~ ~ ~ execute @a[r=47,rm=46] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 46m
execute @e[tag=track] ~ ~ ~ execute @a[r=48,rm=47] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 47m
execute @e[tag=track] ~ ~ ~ execute @a[r=49,rm=48] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 48m
execute @e[tag=track] ~ ~ ~ execute @a[r=50,rm=49] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 49m
execute @e[tag=track] ~ ~ ~ execute @a[r=51,rm=50] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 50m
execute @e[tag=track] ~ ~ ~ execute @a[r=52,rm=51] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 51m
execute @e[tag=track] ~ ~ ~ execute @a[r=53,rm=52] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 52m
execute @e[tag=track] ~ ~ ~ execute @a[r=54,rm=53] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 53m
execute @e[tag=track] ~ ~ ~ execute @a[r=55,rm=54] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 54m
execute @e[tag=track] ~ ~ ~ execute @a[r=56,rm=55] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 55m
execute @e[tag=track] ~ ~ ~ execute @a[r=57,rm=56] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 56m
execute @e[tag=track] ~ ~ ~ execute @a[r=58,rm=57] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 57m
execute @e[tag=track] ~ ~ ~ execute @a[r=59,rm=58] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 58m
execute @e[tag=track] ~ ~ ~ execute @a[r=60,rm=59] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 59m
execute @e[tag=track] ~ ~ ~ execute @a[r=61,rm=60] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 60m
execute @e[tag=track] ~ ~ ~ execute @a[r=62,rm=61] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 61m
execute @e[tag=track] ~ ~ ~ execute @a[r=63,rm=62] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 62m
execute @e[tag=track] ~ ~ ~ execute @a[r=64,rm=63] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 63m
execute @e[tag=track] ~ ~ ~ execute @a[r=65,rm=64] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 64m