#function detecting 8-12 chunks / 129-193 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=130,rm=129] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 129m
execute @e[tag=track] ~ ~ ~ execute @a[r=131,rm=130] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 130m
execute @e[tag=track] ~ ~ ~ execute @a[r=132,rm=131] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 131m
execute @e[tag=track] ~ ~ ~ execute @a[r=133,rm=132] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 132m
execute @e[tag=track] ~ ~ ~ execute @a[r=134,rm=133] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 133m
execute @e[tag=track] ~ ~ ~ execute @a[r=135,rm=134] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 134m
execute @e[tag=track] ~ ~ ~ execute @a[r=136,rm=135] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 135m
execute @e[tag=track] ~ ~ ~ execute @a[r=137,rm=136] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 136m
execute @e[tag=track] ~ ~ ~ execute @a[r=138,rm=137] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 137m
execute @e[tag=track] ~ ~ ~ execute @a[r=139,rm=138] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 138m
execute @e[tag=track] ~ ~ ~ execute @a[r=140,rm=139] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 139m
execute @e[tag=track] ~ ~ ~ execute @a[r=141,rm=140] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 140m
execute @e[tag=track] ~ ~ ~ execute @a[r=142,rm=141] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 141m
execute @e[tag=track] ~ ~ ~ execute @a[r=143,rm=142] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 142m
execute @e[tag=track] ~ ~ ~ execute @a[r=144,rm=143] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 143m
execute @e[tag=track] ~ ~ ~ execute @a[r=145,rm=144] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 144m
execute @e[tag=track] ~ ~ ~ execute @a[r=146,rm=145] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 145m
execute @e[tag=track] ~ ~ ~ execute @a[r=147,rm=146] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 146m
execute @e[tag=track] ~ ~ ~ execute @a[r=148,rm=147] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 147m
execute @e[tag=track] ~ ~ ~ execute @a[r=149,rm=148] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 148m
execute @e[tag=track] ~ ~ ~ execute @a[r=150,rm=149] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 149m
execute @e[tag=track] ~ ~ ~ execute @a[r=151,rm=150] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 150m
execute @e[tag=track] ~ ~ ~ execute @a[r=152,rm=151] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 151m
execute @e[tag=track] ~ ~ ~ execute @a[r=153,rm=152] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 152m
execute @e[tag=track] ~ ~ ~ execute @a[r=154,rm=153] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 153m
execute @e[tag=track] ~ ~ ~ execute @a[r=155,rm=154] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 154m
execute @e[tag=track] ~ ~ ~ execute @a[r=156,rm=155] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 155m
execute @e[tag=track] ~ ~ ~ execute @a[r=157,rm=156] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 156m
execute @e[tag=track] ~ ~ ~ execute @a[r=158,rm=157] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 157m
execute @e[tag=track] ~ ~ ~ execute @a[r=159,rm=158] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 158m
execute @e[tag=track] ~ ~ ~ execute @a[r=160,rm=159] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 159m
execute @e[tag=track] ~ ~ ~ execute @a[r=161,rm=160] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 160m
execute @e[tag=track] ~ ~ ~ execute @a[r=162,rm=161] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 161m
execute @e[tag=track] ~ ~ ~ execute @a[r=163,rm=162] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 162m
execute @e[tag=track] ~ ~ ~ execute @a[r=164,rm=163] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 163m
execute @e[tag=track] ~ ~ ~ execute @a[r=165,rm=164] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 164m
execute @e[tag=track] ~ ~ ~ execute @a[r=166,rm=165] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 165m
execute @e[tag=track] ~ ~ ~ execute @a[r=167,rm=166] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 166m
execute @e[tag=track] ~ ~ ~ execute @a[r=168,rm=167] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 167m
execute @e[tag=track] ~ ~ ~ execute @a[r=169,rm=168] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 168m
execute @e[tag=track] ~ ~ ~ execute @a[r=170,rm=169] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 169m
execute @e[tag=track] ~ ~ ~ execute @a[r=171,rm=170] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 170m
execute @e[tag=track] ~ ~ ~ execute @a[r=172,rm=171] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 171m
execute @e[tag=track] ~ ~ ~ execute @a[r=173,rm=172] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 172m
execute @e[tag=track] ~ ~ ~ execute @a[r=174,rm=173] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 173m
execute @e[tag=track] ~ ~ ~ execute @a[r=175,rm=174] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 174m
execute @e[tag=track] ~ ~ ~ execute @a[r=176,rm=175] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 175m
execute @e[tag=track] ~ ~ ~ execute @a[r=177,rm=176] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 176m
execute @e[tag=track] ~ ~ ~ execute @a[r=178,rm=177] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 177m
execute @e[tag=track] ~ ~ ~ execute @a[r=179,rm=178] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 178m
execute @e[tag=track] ~ ~ ~ execute @a[r=180,rm=179] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 179m
execute @e[tag=track] ~ ~ ~ execute @a[r=181,rm=180] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 180m
execute @e[tag=track] ~ ~ ~ execute @a[r=182,rm=181] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 181m
execute @e[tag=track] ~ ~ ~ execute @a[r=183,rm=182] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 182m
execute @e[tag=track] ~ ~ ~ execute @a[r=184,rm=183] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 183m
execute @e[tag=track] ~ ~ ~ execute @a[r=185,rm=184] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 184m
execute @e[tag=track] ~ ~ ~ execute @a[r=186,rm=185] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 185m
execute @e[tag=track] ~ ~ ~ execute @a[r=187,rm=186] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 186m
execute @e[tag=track] ~ ~ ~ execute @a[r=188,rm=187] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 187m
execute @e[tag=track] ~ ~ ~ execute @a[r=189,rm=188] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 188m
execute @e[tag=track] ~ ~ ~ execute @a[r=190,rm=189] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 189m
execute @e[tag=track] ~ ~ ~ execute @a[r=191,rm=190] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 190m
execute @e[tag=track] ~ ~ ~ execute @a[r=192,rm=191] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 191m
execute @e[tag=track] ~ ~ ~ execute @a[r=193,rm=192] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 192m