#function detecting 13-16 chunks / 193-256 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=194,rm=193] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 193m
execute @e[tag=track] ~ ~ ~ execute @a[r=195,rm=194] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 194m
execute @e[tag=track] ~ ~ ~ execute @a[r=196,rm=195] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 195m
execute @e[tag=track] ~ ~ ~ execute @a[r=197,rm=196] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 196m
execute @e[tag=track] ~ ~ ~ execute @a[r=198,rm=197] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 197m
execute @e[tag=track] ~ ~ ~ execute @a[r=199,rm=198] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 198m
execute @e[tag=track] ~ ~ ~ execute @a[r=200,rm=199] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 199m
execute @e[tag=track] ~ ~ ~ execute @a[r=201,rm=200] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 200m
execute @e[tag=track] ~ ~ ~ execute @a[r=202,rm=201] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 201m
execute @e[tag=track] ~ ~ ~ execute @a[r=203,rm=202] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 202m
execute @e[tag=track] ~ ~ ~ execute @a[r=204,rm=203] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 203m
execute @e[tag=track] ~ ~ ~ execute @a[r=205,rm=204] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 204m
execute @e[tag=track] ~ ~ ~ execute @a[r=206,rm=205] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 205m
execute @e[tag=track] ~ ~ ~ execute @a[r=207,rm=206] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 206m
execute @e[tag=track] ~ ~ ~ execute @a[r=208,rm=207] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 207m
execute @e[tag=track] ~ ~ ~ execute @a[r=209,rm=208] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 208m
execute @e[tag=track] ~ ~ ~ execute @a[r=210,rm=209] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 209m
execute @e[tag=track] ~ ~ ~ execute @a[r=211,rm=210] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 210m
execute @e[tag=track] ~ ~ ~ execute @a[r=212,rm=211] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 211m
execute @e[tag=track] ~ ~ ~ execute @a[r=213,rm=212] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 212m
execute @e[tag=track] ~ ~ ~ execute @a[r=214,rm=213] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 213m
execute @e[tag=track] ~ ~ ~ execute @a[r=215,rm=214] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 214m
execute @e[tag=track] ~ ~ ~ execute @a[r=216,rm=215] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 215m
execute @e[tag=track] ~ ~ ~ execute @a[r=217,rm=216] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 216m
execute @e[tag=track] ~ ~ ~ execute @a[r=218,rm=217] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 222m
execute @e[tag=track] ~ ~ ~ execute @a[r=219,rm=218] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 223m
execute @e[tag=track] ~ ~ ~ execute @a[r=220,rm=219] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 224m
execute @e[tag=track] ~ ~ ~ execute @a[r=221,rm=220] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 220m
execute @e[tag=track] ~ ~ ~ execute @a[r=222,rm=221] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 221m
execute @e[tag=track] ~ ~ ~ execute @a[r=223,rm=222] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 222m
execute @e[tag=track] ~ ~ ~ execute @a[r=224,rm=223] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 223m
execute @e[tag=track] ~ ~ ~ execute @a[r=225,rm=224] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 224m
execute @e[tag=track] ~ ~ ~ execute @a[r=226,rm=225] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 225m
execute @e[tag=track] ~ ~ ~ execute @a[r=227,rm=226] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 226m
execute @e[tag=track] ~ ~ ~ execute @a[r=228,rm=227] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 227m
execute @e[tag=track] ~ ~ ~ execute @a[r=229,rm=228] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 228m
execute @e[tag=track] ~ ~ ~ execute @a[r=230,rm=229] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 229m
execute @e[tag=track] ~ ~ ~ execute @a[r=231,rm=230] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 230m
execute @e[tag=track] ~ ~ ~ execute @a[r=232,rm=231] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 231m
execute @e[tag=track] ~ ~ ~ execute @a[r=233,rm=232] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 232m
execute @e[tag=track] ~ ~ ~ execute @a[r=234,rm=233] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 233m
execute @e[tag=track] ~ ~ ~ execute @a[r=235,rm=234] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 234m
execute @e[tag=track] ~ ~ ~ execute @a[r=236,rm=235] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 235m
execute @e[tag=track] ~ ~ ~ execute @a[r=237,rm=236] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 236m
execute @e[tag=track] ~ ~ ~ execute @a[r=238,rm=237] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 237m
execute @e[tag=track] ~ ~ ~ execute @a[r=239,rm=238] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 238m
execute @e[tag=track] ~ ~ ~ execute @a[r=240,rm=239] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 239m
execute @e[tag=track] ~ ~ ~ execute @a[r=241,rm=240] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 240m
execute @e[tag=track] ~ ~ ~ execute @a[r=242,rm=241] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 241m
execute @e[tag=track] ~ ~ ~ execute @a[r=243,rm=242] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 242m
execute @e[tag=track] ~ ~ ~ execute @a[r=244,rm=243] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 243m
execute @e[tag=track] ~ ~ ~ execute @a[r=245,rm=244] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 244m
execute @e[tag=track] ~ ~ ~ execute @a[r=246,rm=245] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 245m
execute @e[tag=track] ~ ~ ~ execute @a[r=247,rm=246] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 246m
execute @e[tag=track] ~ ~ ~ execute @a[r=248,rm=247] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 247m
execute @e[tag=track] ~ ~ ~ execute @a[r=249,rm=248] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 248m
execute @e[tag=track] ~ ~ ~ execute @a[r=250,rm=249] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 249m
execute @e[tag=track] ~ ~ ~ execute @a[r=251,rm=250] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 250m
execute @e[tag=track] ~ ~ ~ execute @a[r=252,rm=251] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 251m
execute @e[tag=track] ~ ~ ~ execute @a[r=253,rm=252] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 252m
execute @e[tag=track] ~ ~ ~ execute @a[r=254,rm=253] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 253m
execute @e[tag=track] ~ ~ ~ execute @a[r=255,rm=254] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 254m
execute @e[tag=track] ~ ~ ~ execute @a[r=256,rm=255] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 255m
execute @e[tag=track] ~ ~ ~ execute @a[r=257,rm=256] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 256m