#function detecting 17-20 chunks / 257-320 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=258,rm=257] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 257m
execute @e[tag=track] ~ ~ ~ execute @a[r=259,rm=258] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 258m
execute @e[tag=track] ~ ~ ~ execute @a[r=260,rm=259] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 259m
execute @e[tag=track] ~ ~ ~ execute @a[r=261,rm=260] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 260m
execute @e[tag=track] ~ ~ ~ execute @a[r=262,rm=261] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 261m
execute @e[tag=track] ~ ~ ~ execute @a[r=263,rm=262] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 262m
execute @e[tag=track] ~ ~ ~ execute @a[r=264,rm=263] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 263m
execute @e[tag=track] ~ ~ ~ execute @a[r=265,rm=264] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 264m
execute @e[tag=track] ~ ~ ~ execute @a[r=266,rm=265] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 265m
execute @e[tag=track] ~ ~ ~ execute @a[r=267,rm=266] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 266m
execute @e[tag=track] ~ ~ ~ execute @a[r=268,rm=267] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 267m
execute @e[tag=track] ~ ~ ~ execute @a[r=269,rm=268] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 268m
execute @e[tag=track] ~ ~ ~ execute @a[r=270,rm=269] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 269m
execute @e[tag=track] ~ ~ ~ execute @a[r=271,rm=270] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 270m
execute @e[tag=track] ~ ~ ~ execute @a[r=272,rm=271] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 271m
execute @e[tag=track] ~ ~ ~ execute @a[r=273,rm=272] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 272m
execute @e[tag=track] ~ ~ ~ execute @a[r=274,rm=273] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 273m
execute @e[tag=track] ~ ~ ~ execute @a[r=275,rm=274] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 274m
execute @e[tag=track] ~ ~ ~ execute @a[r=276,rm=275] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 275m
execute @e[tag=track] ~ ~ ~ execute @a[r=277,rm=276] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 276m
execute @e[tag=track] ~ ~ ~ execute @a[r=278,rm=277] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 277m
execute @e[tag=track] ~ ~ ~ execute @a[r=279,rm=278] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 278m
execute @e[tag=track] ~ ~ ~ execute @a[r=280,rm=279] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 279m
execute @e[tag=track] ~ ~ ~ execute @a[r=281,rm=280] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 280m
execute @e[tag=track] ~ ~ ~ execute @a[r=282,rm=281] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 281m
execute @e[tag=track] ~ ~ ~ execute @a[r=283,rm=282] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 282m
execute @e[tag=track] ~ ~ ~ execute @a[r=284,rm=283] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 283m
execute @e[tag=track] ~ ~ ~ execute @a[r=285,rm=284] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 284m
execute @e[tag=track] ~ ~ ~ execute @a[r=286,rm=285] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 285m
execute @e[tag=track] ~ ~ ~ execute @a[r=287,rm=286] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 286m
execute @e[tag=track] ~ ~ ~ execute @a[r=288,rm=287] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 287m
execute @e[tag=track] ~ ~ ~ execute @a[r=289,rm=288] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 288m
execute @e[tag=track] ~ ~ ~ execute @a[r=290,rm=289] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 289m
execute @e[tag=track] ~ ~ ~ execute @a[r=291,rm=290] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 290m
execute @e[tag=track] ~ ~ ~ execute @a[r=292,rm=291] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 291m
execute @e[tag=track] ~ ~ ~ execute @a[r=293,rm=292] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 292m
execute @e[tag=track] ~ ~ ~ execute @a[r=294,rm=293] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 293m
execute @e[tag=track] ~ ~ ~ execute @a[r=295,rm=294] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 294m
execute @e[tag=track] ~ ~ ~ execute @a[r=296,rm=295] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 295m
execute @e[tag=track] ~ ~ ~ execute @a[r=297,rm=296] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 296m
execute @e[tag=track] ~ ~ ~ execute @a[r=298,rm=297] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 297m
execute @e[tag=track] ~ ~ ~ execute @a[r=299,rm=298] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 298m
execute @e[tag=track] ~ ~ ~ execute @a[r=300,rm=299] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 299m
execute @e[tag=track] ~ ~ ~ execute @a[r=301,rm=300] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 300m
execute @e[tag=track] ~ ~ ~ execute @a[r=302,rm=301] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 301m
execute @e[tag=track] ~ ~ ~ execute @a[r=303,rm=302] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 302m
execute @e[tag=track] ~ ~ ~ execute @a[r=304,rm=303] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 303m
execute @e[tag=track] ~ ~ ~ execute @a[r=305,rm=304] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 304m
execute @e[tag=track] ~ ~ ~ execute @a[r=306,rm=305] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 305m
execute @e[tag=track] ~ ~ ~ execute @a[r=307,rm=306] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 306m
execute @e[tag=track] ~ ~ ~ execute @a[r=308,rm=307] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 307m
execute @e[tag=track] ~ ~ ~ execute @a[r=309,rm=308] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 308m
execute @e[tag=track] ~ ~ ~ execute @a[r=310,rm=309] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 309m
execute @e[tag=track] ~ ~ ~ execute @a[r=311,rm=310] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 310m
execute @e[tag=track] ~ ~ ~ execute @a[r=312,rm=311] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 311m
execute @e[tag=track] ~ ~ ~ execute @a[r=313,rm=312] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 312m
execute @e[tag=track] ~ ~ ~ execute @a[r=314,rm=313] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 313m
execute @e[tag=track] ~ ~ ~ execute @a[r=315,rm=314] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 314m
execute @e[tag=track] ~ ~ ~ execute @a[r=316,rm=315] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 315m
execute @e[tag=track] ~ ~ ~ execute @a[r=317,rm=316] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 316m
execute @e[tag=track] ~ ~ ~ execute @a[r=318,rm=317] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 317m
execute @e[tag=track] ~ ~ ~ execute @a[r=319,rm=318] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 318m
execute @e[tag=track] ~ ~ ~ execute @a[r=320,rm=319] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 319m
execute @e[tag=track] ~ ~ ~ execute @a[r=321,rm=320] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 320m