#function detecting 13-16 chunks / 385-448 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=386,rm=385] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 385m
execute @e[tag=track] ~ ~ ~ execute @a[r=387,rm=386] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 386m
execute @e[tag=track] ~ ~ ~ execute @a[r=388,rm=387] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 387m
execute @e[tag=track] ~ ~ ~ execute @a[r=389,rm=388] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 388m
execute @e[tag=track] ~ ~ ~ execute @a[r=390,rm=389] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 389m
execute @e[tag=track] ~ ~ ~ execute @a[r=391,rm=390] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 390m
execute @e[tag=track] ~ ~ ~ execute @a[r=392,rm=391] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 391m
execute @e[tag=track] ~ ~ ~ execute @a[r=393,rm=392] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 392m
execute @e[tag=track] ~ ~ ~ execute @a[r=394,rm=393] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 393m
execute @e[tag=track] ~ ~ ~ execute @a[r=395,rm=394] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 394m
execute @e[tag=track] ~ ~ ~ execute @a[r=396,rm=395] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 395m
execute @e[tag=track] ~ ~ ~ execute @a[r=397,rm=396] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 396m
execute @e[tag=track] ~ ~ ~ execute @a[r=398,rm=397] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 397m
execute @e[tag=track] ~ ~ ~ execute @a[r=399,rm=398] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 398m
execute @e[tag=track] ~ ~ ~ execute @a[r=400,rm=399] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 399m
execute @e[tag=track] ~ ~ ~ execute @a[r=401,rm=400] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 400m
execute @e[tag=track] ~ ~ ~ execute @a[r=402,rm=401] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 401m
execute @e[tag=track] ~ ~ ~ execute @a[r=403,rm=402] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 402m
execute @e[tag=track] ~ ~ ~ execute @a[r=404,rm=403] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 403m
execute @e[tag=track] ~ ~ ~ execute @a[r=405,rm=404] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 404m
execute @e[tag=track] ~ ~ ~ execute @a[r=406,rm=405] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 405m
execute @e[tag=track] ~ ~ ~ execute @a[r=407,rm=406] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 406m
execute @e[tag=track] ~ ~ ~ execute @a[r=408,rm=407] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 407m
execute @e[tag=track] ~ ~ ~ execute @a[r=409,rm=408] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 408m
execute @e[tag=track] ~ ~ ~ execute @a[r=410,rm=409] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 409m
execute @e[tag=track] ~ ~ ~ execute @a[r=411,rm=410] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 410m
execute @e[tag=track] ~ ~ ~ execute @a[r=412,rm=411] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 411m
execute @e[tag=track] ~ ~ ~ execute @a[r=413,rm=412] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 412m
execute @e[tag=track] ~ ~ ~ execute @a[r=414,rm=413] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 413m
execute @e[tag=track] ~ ~ ~ execute @a[r=415,rm=414] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 414m
execute @e[tag=track] ~ ~ ~ execute @a[r=416,rm=415] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 415m
execute @e[tag=track] ~ ~ ~ execute @a[r=417,rm=416] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 416m
execute @e[tag=track] ~ ~ ~ execute @a[r=418,rm=417] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 417m
execute @e[tag=track] ~ ~ ~ execute @a[r=419,rm=418] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 418m
execute @e[tag=track] ~ ~ ~ execute @a[r=420,rm=419] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 419m
execute @e[tag=track] ~ ~ ~ execute @a[r=421,rm=420] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 420m
execute @e[tag=track] ~ ~ ~ execute @a[r=422,rm=421] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 421m
execute @e[tag=track] ~ ~ ~ execute @a[r=423,rm=422] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 422m
execute @e[tag=track] ~ ~ ~ execute @a[r=424,rm=423] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 423m
execute @e[tag=track] ~ ~ ~ execute @a[r=425,rm=424] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 424m
execute @e[tag=track] ~ ~ ~ execute @a[r=426,rm=425] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 425m
execute @e[tag=track] ~ ~ ~ execute @a[r=427,rm=426] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 426m
execute @e[tag=track] ~ ~ ~ execute @a[r=428,rm=427] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 427m
execute @e[tag=track] ~ ~ ~ execute @a[r=429,rm=428] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 428m
execute @e[tag=track] ~ ~ ~ execute @a[r=430,rm=429] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 429m
execute @e[tag=track] ~ ~ ~ execute @a[r=431,rm=430] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 430m
execute @e[tag=track] ~ ~ ~ execute @a[r=432,rm=431] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 431m
execute @e[tag=track] ~ ~ ~ execute @a[r=433,rm=432] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 432m
execute @e[tag=track] ~ ~ ~ execute @a[r=434,rm=433] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 433m
execute @e[tag=track] ~ ~ ~ execute @a[r=435,rm=434] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 434m
execute @e[tag=track] ~ ~ ~ execute @a[r=436,rm=435] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 435m
execute @e[tag=track] ~ ~ ~ execute @a[r=437,rm=436] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 436m
execute @e[tag=track] ~ ~ ~ execute @a[r=438,rm=437] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 437m
execute @e[tag=track] ~ ~ ~ execute @a[r=439,rm=438] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 438m
execute @e[tag=track] ~ ~ ~ execute @a[r=440,rm=439] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 439m
execute @e[tag=track] ~ ~ ~ execute @a[r=441,rm=440] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 440m
execute @e[tag=track] ~ ~ ~ execute @a[r=442,rm=441] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 441m
execute @e[tag=track] ~ ~ ~ execute @a[r=443,rm=442] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 442m
execute @e[tag=track] ~ ~ ~ execute @a[r=444,rm=443] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 443m
execute @e[tag=track] ~ ~ ~ execute @a[r=445,rm=444] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 444m
execute @e[tag=track] ~ ~ ~ execute @a[r=446,rm=445] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 445m
execute @e[tag=track] ~ ~ ~ execute @a[r=447,rm=446] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 446m
execute @e[tag=track] ~ ~ ~ execute @a[r=448,rm=447] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 447m
execute @e[tag=track] ~ ~ ~ execute @a[r=449,rm=448] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 448m