execute @e[tag=track] ~ ~ ~ execute @a[r=1,rm=0] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 0m
execute @e[tag=track] ~ ~ ~ execute @a[r=2,rm=1] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1m
execute @e[tag=track] ~ ~ ~ execute @a[r=3,rm=2] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 2m
execute @e[tag=track] ~ ~ ~ execute @a[r=4,rm=3] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 3m
execute @e[tag=track] ~ ~ ~ execute @a[r=5,rm=4] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 4m
execute @e[tag=track] ~ ~ ~ execute @a[r=6,rm=5] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 5m
execute @e[tag=track] ~ ~ ~ execute @a[r=7,rm=6] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 6m
execute @e[tag=track] ~ ~ ~ execute @a[r=8,rm=7] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 7m
execute @e[tag=track] ~ ~ ~ execute @a[r=9,rm=8] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 8m
execute @e[tag=track] ~ ~ ~ execute @a[r=10,rm=9] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 9m
execute @e[tag=track] ~ ~ ~ execute @a[r=11,rm=10] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 10m
execute @e[tag=track] ~ ~ ~ execute @a[r=12,rm=11] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 11m
execute @e[tag=track] ~ ~ ~ execute @a[r=13,rm=12] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 12m
execute @e[tag=track] ~ ~ ~ execute @a[r=14,rm=13] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 13m
execute @e[tag=track] ~ ~ ~ execute @a[r=15,rm=14] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 14m
execute @e[tag=track] ~ ~ ~ execute @a[r=16,rm=15] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 15m
execute @e[tag=track] ~ ~ ~ execute @a[r=17,rm=16] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 16m
execute @e[tag=track] ~ ~ ~ execute @a[r=18,rm=17] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 17m
execute @e[tag=track] ~ ~ ~ execute @a[r=19,rm=18] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 18m
execute @e[tag=track] ~ ~ ~ execute @a[r=20,rm=19] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 19m
execute @e[tag=track] ~ ~ ~ execute @a[r=21,rm=20] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 20m
execute @e[tag=track] ~ ~ ~ execute @a[r=22,rm=21] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 21m
execute @e[tag=track] ~ ~ ~ execute @a[r=23,rm=22] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 22m
execute @e[tag=track] ~ ~ ~ execute @a[r=24,rm=23] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 23m
execute @e[tag=track] ~ ~ ~ execute @a[r=25,rm=24] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 24m
execute @e[tag=track] ~ ~ ~ execute @a[r=26,rm=25] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 25m
execute @e[tag=track] ~ ~ ~ execute @a[r=27,rm=26] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 26m
execute @e[tag=track] ~ ~ ~ execute @a[r=28,rm=27] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 27m
execute @e[tag=track] ~ ~ ~ execute @a[r=29,rm=28] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 28m
execute @e[tag=track] ~ ~ ~ execute @a[r=30,rm=29] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 29m
execute @e[tag=track] ~ ~ ~ execute @a[r=31,rm=30] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 30m
execute @e[tag=track] ~ ~ ~ execute @a[r=32,rm=31] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 31m
execute @e[tag=track] ~ ~ ~ execute @a[r=33,rm=32] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 32m
execute @e[tag=track] ~ ~ ~ execute @a[r=34,rm=33] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 33m
execute @e[tag=track] ~ ~ ~ execute @a[r=35,rm=34] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 34m
execute @e[tag=track] ~ ~ ~ execute @a[r=36,rm=35] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 35m
execute @e[tag=track] ~ ~ ~ execute @a[r=37,rm=36] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 36m
execute @e[tag=track] ~ ~ ~ execute @a[r=38,rm=37] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 37m
execute @e[tag=track] ~ ~ ~ execute @a[r=39,rm=38] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 38m
execute @e[tag=track] ~ ~ ~ execute @a[r=40,rm=39] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 39m
execute @e[tag=track] ~ ~ ~ execute @a[r=41,rm=40] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 40m
execute @e[tag=track] ~ ~ ~ execute @a[r=42,rm=41] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 41m
execute @e[tag=track] ~ ~ ~ execute @a[r=43,rm=42] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 42m
execute @e[tag=track] ~ ~ ~ execute @a[r=44,rm=43] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 43m
execute @e[tag=track] ~ ~ ~ execute @a[r=45,rm=44] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 44m
execute @e[tag=track] ~ ~ ~ execute @a[r=46,rm=45] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 45m
execute @e[tag=track] ~ ~ ~ execute @a[r=47,rm=46] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 46m
execute @e[tag=track] ~ ~ ~ execute @a[r=48,rm=47] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 47m
execute @e[tag=track] ~ ~ ~ execute @a[r=49,rm=48] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 48m
execute @e[tag=track] ~ ~ ~ execute @a[r=50,rm=49] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 49m
execute @e[tag=track] ~ ~ ~ execute @a[r=51,rm=50] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 50m
execute @e[tag=track] ~ ~ ~ execute @a[r=52,rm=51] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 51m
execute @e[tag=track] ~ ~ ~ execute @a[r=53,rm=52] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 52m
execute @e[tag=track] ~ ~ ~ execute @a[r=54,rm=53] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 53m
execute @e[tag=track] ~ ~ ~ execute @a[r=55,rm=54] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 54m
execute @e[tag=track] ~ ~ ~ execute @a[r=56,rm=55] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 55m
execute @e[tag=track] ~ ~ ~ execute @a[r=57,rm=56] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 56m
execute @e[tag=track] ~ ~ ~ execute @a[r=58,rm=57] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 57m
execute @e[tag=track] ~ ~ ~ execute @a[r=59,rm=58] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 58m
execute @e[tag=track] ~ ~ ~ execute @a[r=60,rm=59] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 59m
execute @e[tag=track] ~ ~ ~ execute @a[r=61,rm=60] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 60m
execute @e[tag=track] ~ ~ ~ execute @a[r=62,rm=61] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 61m
execute @e[tag=track] ~ ~ ~ execute @a[r=63,rm=62] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 62m
execute @e[tag=track] ~ ~ ~ execute @a[r=64,rm=63] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 63m
execute @e[tag=track] ~ ~ ~ execute @a[r=65,rm=64] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 64m
execute @e[tag=track] ~ ~ ~ execute @a[r=66,rm=65] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 65m
execute @e[tag=track] ~ ~ ~ execute @a[r=67,rm=66] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 66m
execute @e[tag=track] ~ ~ ~ execute @a[r=68,rm=67] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 67m
execute @e[tag=track] ~ ~ ~ execute @a[r=69,rm=68] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 68m
execute @e[tag=track] ~ ~ ~ execute @a[r=70,rm=69] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 69m
execute @e[tag=track] ~ ~ ~ execute @a[r=71,rm=70] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 70m
execute @e[tag=track] ~ ~ ~ execute @a[r=72,rm=71] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 71m
execute @e[tag=track] ~ ~ ~ execute @a[r=73,rm=72] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 72m
execute @e[tag=track] ~ ~ ~ execute @a[r=74,rm=73] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 73m
execute @e[tag=track] ~ ~ ~ execute @a[r=75,rm=74] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 74m
execute @e[tag=track] ~ ~ ~ execute @a[r=76,rm=75] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 75m
execute @e[tag=track] ~ ~ ~ execute @a[r=77,rm=76] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 76m
execute @e[tag=track] ~ ~ ~ execute @a[r=78,rm=77] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 77m
execute @e[tag=track] ~ ~ ~ execute @a[r=79,rm=78] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 78m
execute @e[tag=track] ~ ~ ~ execute @a[r=80,rm=79] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 79m
execute @e[tag=track] ~ ~ ~ execute @a[r=81,rm=80] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 80m
execute @e[tag=track] ~ ~ ~ execute @a[r=82,rm=81] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 81m
execute @e[tag=track] ~ ~ ~ execute @a[r=83,rm=82] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 82m
execute @e[tag=track] ~ ~ ~ execute @a[r=84,rm=83] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 83m
execute @e[tag=track] ~ ~ ~ execute @a[r=85,rm=84] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 84m
execute @e[tag=track] ~ ~ ~ execute @a[r=86,rm=85] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 85m
execute @e[tag=track] ~ ~ ~ execute @a[r=87,rm=86] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 86m
execute @e[tag=track] ~ ~ ~ execute @a[r=88,rm=87] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 87m
execute @e[tag=track] ~ ~ ~ execute @a[r=89,rm=88] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 88m
execute @e[tag=track] ~ ~ ~ execute @a[r=90,rm=89] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 89m
execute @e[tag=track] ~ ~ ~ execute @a[r=91,rm=90] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 90m
execute @e[tag=track] ~ ~ ~ execute @a[r=92,rm=91] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 91m
execute @e[tag=track] ~ ~ ~ execute @a[r=93,rm=92] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 92m
execute @e[tag=track] ~ ~ ~ execute @a[r=94,rm=93] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 93m
execute @e[tag=track] ~ ~ ~ execute @a[r=95,rm=94] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 94m
execute @e[tag=track] ~ ~ ~ execute @a[r=96,rm=95] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 95m
execute @e[tag=track] ~ ~ ~ execute @a[r=97,rm=96] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 96m
execute @e[tag=track] ~ ~ ~ execute @a[r=98,rm=97] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 97m
execute @e[tag=track] ~ ~ ~ execute @a[r=99,rm=98] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 98m
execute @e[tag=track] ~ ~ ~ execute @a[r=100,rm=99] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 99m
execute @e[tag=track] ~ ~ ~ execute @a[r=101,rm=100] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 100m
execute @e[tag=track] ~ ~ ~ execute @a[r=102,rm=101] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 101m
execute @e[tag=track] ~ ~ ~ execute @a[r=103,rm=102] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 102m
execute @e[tag=track] ~ ~ ~ execute @a[r=104,rm=103] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 103m
execute @e[tag=track] ~ ~ ~ execute @a[r=105,rm=104] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 104m
execute @e[tag=track] ~ ~ ~ execute @a[r=106,rm=105] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 105m
execute @e[tag=track] ~ ~ ~ execute @a[r=107,rm=106] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 106m
execute @e[tag=track] ~ ~ ~ execute @a[r=108,rm=107] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 107m
execute @e[tag=track] ~ ~ ~ execute @a[r=109,rm=108] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 108m
execute @e[tag=track] ~ ~ ~ execute @a[r=110,rm=109] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 109m
execute @e[tag=track] ~ ~ ~ execute @a[r=111,rm=110] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 110m
execute @e[tag=track] ~ ~ ~ execute @a[r=112,rm=111] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 111m
execute @e[tag=track] ~ ~ ~ execute @a[r=113,rm=112] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 112m
execute @e[tag=track] ~ ~ ~ execute @a[r=114,rm=113] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 113m
execute @e[tag=track] ~ ~ ~ execute @a[r=115,rm=114] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 114m
execute @e[tag=track] ~ ~ ~ execute @a[r=116,rm=115] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 115m
execute @e[tag=track] ~ ~ ~ execute @a[r=117,rm=116] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 116m
execute @e[tag=track] ~ ~ ~ execute @a[r=118,rm=117] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 117m
execute @e[tag=track] ~ ~ ~ execute @a[r=119,rm=118] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 118m
execute @e[tag=track] ~ ~ ~ execute @a[r=120,rm=119] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 119m
execute @e[tag=track] ~ ~ ~ execute @a[r=121,rm=120] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 120m
execute @e[tag=track] ~ ~ ~ execute @a[r=122,rm=121] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 121m
execute @e[tag=track] ~ ~ ~ execute @a[r=123,rm=122] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 122m
execute @e[tag=track] ~ ~ ~ execute @a[r=124,rm=123] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 123m
execute @e[tag=track] ~ ~ ~ execute @a[r=125,rm=124] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 124m
execute @e[tag=track] ~ ~ ~ execute @a[r=126,rm=125] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 125m
execute @e[tag=track] ~ ~ ~ execute @a[r=127,rm=126] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 126m
execute @e[tag=track] ~ ~ ~ execute @a[r=128,rm=127] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 127m
execute @e[tag=track] ~ ~ ~ execute @a[r=129,rm=128] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 128m
execute @e[tag=track] ~ ~ ~ execute @a[r=130,rm=129] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 129m
execute @e[tag=track] ~ ~ ~ execute @a[r=131,rm=130] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 130m
execute @e[tag=track] ~ ~ ~ execute @a[r=132,rm=131] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 131m
execute @e[tag=track] ~ ~ ~ execute @a[r=133,rm=132] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 132m
execute @e[tag=track] ~ ~ ~ execute @a[r=134,rm=133] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 133m
execute @e[tag=track] ~ ~ ~ execute @a[r=135,rm=134] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 134m
execute @e[tag=track] ~ ~ ~ execute @a[r=136,rm=135] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 135m
execute @e[tag=track] ~ ~ ~ execute @a[r=137,rm=136] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 136m
execute @e[tag=track] ~ ~ ~ execute @a[r=138,rm=137] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 137m
execute @e[tag=track] ~ ~ ~ execute @a[r=139,rm=138] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 138m
execute @e[tag=track] ~ ~ ~ execute @a[r=140,rm=139] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 139m
execute @e[tag=track] ~ ~ ~ execute @a[r=141,rm=140] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 140m
execute @e[tag=track] ~ ~ ~ execute @a[r=142,rm=141] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 141m
execute @e[tag=track] ~ ~ ~ execute @a[r=143,rm=142] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 142m
execute @e[tag=track] ~ ~ ~ execute @a[r=144,rm=143] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 143m
execute @e[tag=track] ~ ~ ~ execute @a[r=145,rm=144] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 144m
execute @e[tag=track] ~ ~ ~ execute @a[r=146,rm=145] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 145m
execute @e[tag=track] ~ ~ ~ execute @a[r=147,rm=146] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 146m
execute @e[tag=track] ~ ~ ~ execute @a[r=148,rm=147] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 147m
execute @e[tag=track] ~ ~ ~ execute @a[r=149,rm=148] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 148m
execute @e[tag=track] ~ ~ ~ execute @a[r=150,rm=149] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 149m
execute @e[tag=track] ~ ~ ~ execute @a[r=151,rm=150] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 150m
execute @e[tag=track] ~ ~ ~ execute @a[r=152,rm=151] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 151m
execute @e[tag=track] ~ ~ ~ execute @a[r=153,rm=152] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 152m
execute @e[tag=track] ~ ~ ~ execute @a[r=154,rm=153] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 153m
execute @e[tag=track] ~ ~ ~ execute @a[r=155,rm=154] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 154m
execute @e[tag=track] ~ ~ ~ execute @a[r=156,rm=155] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 155m
execute @e[tag=track] ~ ~ ~ execute @a[r=157,rm=156] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 156m
execute @e[tag=track] ~ ~ ~ execute @a[r=158,rm=157] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 157m
execute @e[tag=track] ~ ~ ~ execute @a[r=159,rm=158] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 158m
execute @e[tag=track] ~ ~ ~ execute @a[r=160,rm=159] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 159m
execute @e[tag=track] ~ ~ ~ execute @a[r=161,rm=160] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 160m
execute @e[tag=track] ~ ~ ~ execute @a[r=162,rm=161] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 161m
execute @e[tag=track] ~ ~ ~ execute @a[r=163,rm=162] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 162m
execute @e[tag=track] ~ ~ ~ execute @a[r=164,rm=163] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 163m
execute @e[tag=track] ~ ~ ~ execute @a[r=165,rm=164] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 164m
execute @e[tag=track] ~ ~ ~ execute @a[r=166,rm=165] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 165m
execute @e[tag=track] ~ ~ ~ execute @a[r=167,rm=166] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 166m
execute @e[tag=track] ~ ~ ~ execute @a[r=168,rm=167] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 167m
execute @e[tag=track] ~ ~ ~ execute @a[r=169,rm=168] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 168m
execute @e[tag=track] ~ ~ ~ execute @a[r=170,rm=169] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 169m
execute @e[tag=track] ~ ~ ~ execute @a[r=171,rm=170] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 170m
execute @e[tag=track] ~ ~ ~ execute @a[r=172,rm=171] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 171m
execute @e[tag=track] ~ ~ ~ execute @a[r=173,rm=172] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 172m
execute @e[tag=track] ~ ~ ~ execute @a[r=174,rm=173] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 173m
execute @e[tag=track] ~ ~ ~ execute @a[r=175,rm=174] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 174m
execute @e[tag=track] ~ ~ ~ execute @a[r=176,rm=175] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 175m
execute @e[tag=track] ~ ~ ~ execute @a[r=177,rm=176] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 176m
execute @e[tag=track] ~ ~ ~ execute @a[r=178,rm=177] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 177m
execute @e[tag=track] ~ ~ ~ execute @a[r=179,rm=178] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 178m
execute @e[tag=track] ~ ~ ~ execute @a[r=180,rm=179] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 179m
execute @e[tag=track] ~ ~ ~ execute @a[r=181,rm=180] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 180m
execute @e[tag=track] ~ ~ ~ execute @a[r=182,rm=181] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 181m
execute @e[tag=track] ~ ~ ~ execute @a[r=183,rm=182] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 182m
execute @e[tag=track] ~ ~ ~ execute @a[r=184,rm=183] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 183m
execute @e[tag=track] ~ ~ ~ execute @a[r=185,rm=184] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 184m
execute @e[tag=track] ~ ~ ~ execute @a[r=186,rm=185] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 185m
execute @e[tag=track] ~ ~ ~ execute @a[r=187,rm=186] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 186m
execute @e[tag=track] ~ ~ ~ execute @a[r=188,rm=187] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 187m
execute @e[tag=track] ~ ~ ~ execute @a[r=189,rm=188] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 188m
execute @e[tag=track] ~ ~ ~ execute @a[r=190,rm=189] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 189m
execute @e[tag=track] ~ ~ ~ execute @a[r=191,rm=190] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 190m
execute @e[tag=track] ~ ~ ~ execute @a[r=192,rm=191] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 191m
execute @e[tag=track] ~ ~ ~ execute @a[r=193,rm=192] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 192m
execute @e[tag=track] ~ ~ ~ execute @a[r=194,rm=193] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 193m
execute @e[tag=track] ~ ~ ~ execute @a[r=195,rm=194] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 194m
execute @e[tag=track] ~ ~ ~ execute @a[r=196,rm=195] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 195m
execute @e[tag=track] ~ ~ ~ execute @a[r=197,rm=196] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 196m
execute @e[tag=track] ~ ~ ~ execute @a[r=198,rm=197] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 197m
execute @e[tag=track] ~ ~ ~ execute @a[r=199,rm=198] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 198m
execute @e[tag=track] ~ ~ ~ execute @a[r=200,rm=199] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 199m
execute @e[tag=track] ~ ~ ~ execute @a[r=201,rm=200] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 200m
execute @e[tag=track] ~ ~ ~ execute @a[r=202,rm=201] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 201m
execute @e[tag=track] ~ ~ ~ execute @a[r=203,rm=202] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 202m
execute @e[tag=track] ~ ~ ~ execute @a[r=204,rm=203] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 203m
execute @e[tag=track] ~ ~ ~ execute @a[r=205,rm=204] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 204m
execute @e[tag=track] ~ ~ ~ execute @a[r=206,rm=205] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 205m
execute @e[tag=track] ~ ~ ~ execute @a[r=207,rm=206] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 206m
execute @e[tag=track] ~ ~ ~ execute @a[r=208,rm=207] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 207m
execute @e[tag=track] ~ ~ ~ execute @a[r=209,rm=208] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 208m
execute @e[tag=track] ~ ~ ~ execute @a[r=210,rm=209] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 209m
execute @e[tag=track] ~ ~ ~ execute @a[r=211,rm=210] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 210m
execute @e[tag=track] ~ ~ ~ execute @a[r=212,rm=211] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 211m
execute @e[tag=track] ~ ~ ~ execute @a[r=213,rm=212] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 212m
execute @e[tag=track] ~ ~ ~ execute @a[r=214,rm=213] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 213m
execute @e[tag=track] ~ ~ ~ execute @a[r=215,rm=214] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 214m
execute @e[tag=track] ~ ~ ~ execute @a[r=216,rm=215] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 215m
execute @e[tag=track] ~ ~ ~ execute @a[r=217,rm=216] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 216m
execute @e[tag=track] ~ ~ ~ execute @a[r=218,rm=217] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 222m
execute @e[tag=track] ~ ~ ~ execute @a[r=219,rm=218] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 223m
execute @e[tag=track] ~ ~ ~ execute @a[r=220,rm=219] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 224m
execute @e[tag=track] ~ ~ ~ execute @a[r=221,rm=220] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 220m
execute @e[tag=track] ~ ~ ~ execute @a[r=222,rm=221] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 221m
execute @e[tag=track] ~ ~ ~ execute @a[r=223,rm=222] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 222m
execute @e[tag=track] ~ ~ ~ execute @a[r=224,rm=223] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 223m
execute @e[tag=track] ~ ~ ~ execute @a[r=225,rm=224] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 224m
execute @e[tag=track] ~ ~ ~ execute @a[r=226,rm=225] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 225m
execute @e[tag=track] ~ ~ ~ execute @a[r=227,rm=226] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 226m
execute @e[tag=track] ~ ~ ~ execute @a[r=228,rm=227] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 227m
execute @e[tag=track] ~ ~ ~ execute @a[r=229,rm=228] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 228m
execute @e[tag=track] ~ ~ ~ execute @a[r=230,rm=229] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 229m
execute @e[tag=track] ~ ~ ~ execute @a[r=231,rm=230] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 230m
execute @e[tag=track] ~ ~ ~ execute @a[r=232,rm=231] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 231m
execute @e[tag=track] ~ ~ ~ execute @a[r=233,rm=232] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 232m
execute @e[tag=track] ~ ~ ~ execute @a[r=234,rm=233] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 233m
execute @e[tag=track] ~ ~ ~ execute @a[r=235,rm=234] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 234m
execute @e[tag=track] ~ ~ ~ execute @a[r=236,rm=235] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 235m
execute @e[tag=track] ~ ~ ~ execute @a[r=237,rm=236] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 236m
execute @e[tag=track] ~ ~ ~ execute @a[r=238,rm=237] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 237m
execute @e[tag=track] ~ ~ ~ execute @a[r=239,rm=238] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 238m
execute @e[tag=track] ~ ~ ~ execute @a[r=240,rm=239] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 239m
execute @e[tag=track] ~ ~ ~ execute @a[r=241,rm=240] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 240m
execute @e[tag=track] ~ ~ ~ execute @a[r=242,rm=241] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 241m
execute @e[tag=track] ~ ~ ~ execute @a[r=243,rm=242] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 242m
execute @e[tag=track] ~ ~ ~ execute @a[r=244,rm=243] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 243m
execute @e[tag=track] ~ ~ ~ execute @a[r=245,rm=244] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 244m
execute @e[tag=track] ~ ~ ~ execute @a[r=246,rm=245] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 245m
execute @e[tag=track] ~ ~ ~ execute @a[r=247,rm=246] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 246m
execute @e[tag=track] ~ ~ ~ execute @a[r=248,rm=247] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 247m
execute @e[tag=track] ~ ~ ~ execute @a[r=249,rm=248] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 248m
execute @e[tag=track] ~ ~ ~ execute @a[r=250,rm=249] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 249m
execute @e[tag=track] ~ ~ ~ execute @a[r=251,rm=250] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 250m
execute @e[tag=track] ~ ~ ~ execute @a[r=252,rm=251] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 251m
execute @e[tag=track] ~ ~ ~ execute @a[r=253,rm=252] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 252m
execute @e[tag=track] ~ ~ ~ execute @a[r=254,rm=253] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 253m
execute @e[tag=track] ~ ~ ~ execute @a[r=255,rm=254] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 254m
execute @e[tag=track] ~ ~ ~ execute @a[r=256,rm=255] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 255m
execute @e[tag=track] ~ ~ ~ execute @a[r=257,rm=256] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 256m