#function detecting 13-16 chunks / 321-384 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=322,rm=321] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 321m
execute @e[tag=track] ~ ~ ~ execute @a[r=323,rm=322] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 322m
execute @e[tag=track] ~ ~ ~ execute @a[r=324,rm=323] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 323m
execute @e[tag=track] ~ ~ ~ execute @a[r=325,rm=324] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 324m
execute @e[tag=track] ~ ~ ~ execute @a[r=326,rm=325] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 325m
execute @e[tag=track] ~ ~ ~ execute @a[r=327,rm=326] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 326m
execute @e[tag=track] ~ ~ ~ execute @a[r=328,rm=327] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 327m
execute @e[tag=track] ~ ~ ~ execute @a[r=329,rm=328] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 328m
execute @e[tag=track] ~ ~ ~ execute @a[r=330,rm=329] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 329m
execute @e[tag=track] ~ ~ ~ execute @a[r=331,rm=330] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 330m
execute @e[tag=track] ~ ~ ~ execute @a[r=332,rm=331] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 331m
execute @e[tag=track] ~ ~ ~ execute @a[r=333,rm=332] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 332m
execute @e[tag=track] ~ ~ ~ execute @a[r=334,rm=333] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 333m
execute @e[tag=track] ~ ~ ~ execute @a[r=335,rm=334] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 334m
execute @e[tag=track] ~ ~ ~ execute @a[r=336,rm=335] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 335m
execute @e[tag=track] ~ ~ ~ execute @a[r=337,rm=336] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 336m
execute @e[tag=track] ~ ~ ~ execute @a[r=338,rm=337] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 337m
execute @e[tag=track] ~ ~ ~ execute @a[r=339,rm=338] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 338m
execute @e[tag=track] ~ ~ ~ execute @a[r=340,rm=339] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 339m
execute @e[tag=track] ~ ~ ~ execute @a[r=341,rm=340] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 340m
execute @e[tag=track] ~ ~ ~ execute @a[r=342,rm=341] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 341m
execute @e[tag=track] ~ ~ ~ execute @a[r=343,rm=342] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 342m
execute @e[tag=track] ~ ~ ~ execute @a[r=344,rm=343] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 343m
execute @e[tag=track] ~ ~ ~ execute @a[r=345,rm=344] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 344m
execute @e[tag=track] ~ ~ ~ execute @a[r=346,rm=345] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 345m
execute @e[tag=track] ~ ~ ~ execute @a[r=347,rm=346] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 346m
execute @e[tag=track] ~ ~ ~ execute @a[r=348,rm=347] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 347m
execute @e[tag=track] ~ ~ ~ execute @a[r=349,rm=348] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 348m
execute @e[tag=track] ~ ~ ~ execute @a[r=350,rm=349] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 349m
execute @e[tag=track] ~ ~ ~ execute @a[r=351,rm=350] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 350m
execute @e[tag=track] ~ ~ ~ execute @a[r=352,rm=351] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 351m
execute @e[tag=track] ~ ~ ~ execute @a[r=353,rm=352] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 352m
execute @e[tag=track] ~ ~ ~ execute @a[r=354,rm=353] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 353m
execute @e[tag=track] ~ ~ ~ execute @a[r=355,rm=354] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 354m
execute @e[tag=track] ~ ~ ~ execute @a[r=356,rm=355] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 355m
execute @e[tag=track] ~ ~ ~ execute @a[r=357,rm=356] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 356m
execute @e[tag=track] ~ ~ ~ execute @a[r=358,rm=357] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 357m
execute @e[tag=track] ~ ~ ~ execute @a[r=359,rm=358] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 358m
execute @e[tag=track] ~ ~ ~ execute @a[r=360,rm=359] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 359m
execute @e[tag=track] ~ ~ ~ execute @a[r=361,rm=360] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 360m
execute @e[tag=track] ~ ~ ~ execute @a[r=362,rm=361] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 361m
execute @e[tag=track] ~ ~ ~ execute @a[r=363,rm=362] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 362m
execute @e[tag=track] ~ ~ ~ execute @a[r=364,rm=363] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 363m
execute @e[tag=track] ~ ~ ~ execute @a[r=365,rm=364] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 364m
execute @e[tag=track] ~ ~ ~ execute @a[r=366,rm=365] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 365m
execute @e[tag=track] ~ ~ ~ execute @a[r=367,rm=366] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 366m
execute @e[tag=track] ~ ~ ~ execute @a[r=368,rm=367] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 367m
execute @e[tag=track] ~ ~ ~ execute @a[r=369,rm=368] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 368m
execute @e[tag=track] ~ ~ ~ execute @a[r=370,rm=369] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 369m
execute @e[tag=track] ~ ~ ~ execute @a[r=371,rm=370] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 370m
execute @e[tag=track] ~ ~ ~ execute @a[r=372,rm=371] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 371m
execute @e[tag=track] ~ ~ ~ execute @a[r=373,rm=372] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 372m
execute @e[tag=track] ~ ~ ~ execute @a[r=374,rm=373] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 373m
execute @e[tag=track] ~ ~ ~ execute @a[r=375,rm=374] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 374m
execute @e[tag=track] ~ ~ ~ execute @a[r=376,rm=375] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 375m
execute @e[tag=track] ~ ~ ~ execute @a[r=377,rm=376] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 376m
execute @e[tag=track] ~ ~ ~ execute @a[r=378,rm=377] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 377m
execute @e[tag=track] ~ ~ ~ execute @a[r=379,rm=378] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 378m
execute @e[tag=track] ~ ~ ~ execute @a[r=380,rm=379] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 379m
execute @e[tag=track] ~ ~ ~ execute @a[r=381,rm=380] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 380m
execute @e[tag=track] ~ ~ ~ execute @a[r=382,rm=381] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 381m
execute @e[tag=track] ~ ~ ~ execute @a[r=383,rm=382] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 382m
execute @e[tag=track] ~ ~ ~ execute @a[r=384,rm=383] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 383m
execute @e[tag=track] ~ ~ ~ execute @a[r=385,rm=384] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 384m