#function detecting 13-16 chunks / 449-512 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=450,rm=449] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 449m
execute @e[tag=track] ~ ~ ~ execute @a[r=451,rm=450] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 450m
execute @e[tag=track] ~ ~ ~ execute @a[r=452,rm=451] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 451m
execute @e[tag=track] ~ ~ ~ execute @a[r=453,rm=452] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 452m
execute @e[tag=track] ~ ~ ~ execute @a[r=454,rm=453] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 453m
execute @e[tag=track] ~ ~ ~ execute @a[r=455,rm=454] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 454m
execute @e[tag=track] ~ ~ ~ execute @a[r=456,rm=455] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 455m
execute @e[tag=track] ~ ~ ~ execute @a[r=457,rm=456] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 456m
execute @e[tag=track] ~ ~ ~ execute @a[r=458,rm=457] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 457m
execute @e[tag=track] ~ ~ ~ execute @a[r=459,rm=458] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 458m
execute @e[tag=track] ~ ~ ~ execute @a[r=460,rm=459] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 459m
execute @e[tag=track] ~ ~ ~ execute @a[r=461,rm=460] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 460m
execute @e[tag=track] ~ ~ ~ execute @a[r=462,rm=461] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 461m
execute @e[tag=track] ~ ~ ~ execute @a[r=463,rm=462] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 462m
execute @e[tag=track] ~ ~ ~ execute @a[r=464,rm=463] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 463m
execute @e[tag=track] ~ ~ ~ execute @a[r=465,rm=464] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 464m
execute @e[tag=track] ~ ~ ~ execute @a[r=466,rm=465] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 465m
execute @e[tag=track] ~ ~ ~ execute @a[r=467,rm=466] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 466m
execute @e[tag=track] ~ ~ ~ execute @a[r=468,rm=467] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 467m
execute @e[tag=track] ~ ~ ~ execute @a[r=469,rm=468] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 468m
execute @e[tag=track] ~ ~ ~ execute @a[r=470,rm=469] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 469m
execute @e[tag=track] ~ ~ ~ execute @a[r=471,rm=470] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 470m
execute @e[tag=track] ~ ~ ~ execute @a[r=472,rm=471] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 471m
execute @e[tag=track] ~ ~ ~ execute @a[r=473,rm=472] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 472m
execute @e[tag=track] ~ ~ ~ execute @a[r=474,rm=473] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 473m
execute @e[tag=track] ~ ~ ~ execute @a[r=475,rm=474] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 474m
execute @e[tag=track] ~ ~ ~ execute @a[r=476,rm=475] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 475m
execute @e[tag=track] ~ ~ ~ execute @a[r=477,rm=476] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 476m
execute @e[tag=track] ~ ~ ~ execute @a[r=478,rm=477] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 477m
execute @e[tag=track] ~ ~ ~ execute @a[r=479,rm=478] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 478m
execute @e[tag=track] ~ ~ ~ execute @a[r=480,rm=479] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 479m
execute @e[tag=track] ~ ~ ~ execute @a[r=481,rm=480] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 480m
execute @e[tag=track] ~ ~ ~ execute @a[r=482,rm=481] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 481m
execute @e[tag=track] ~ ~ ~ execute @a[r=483,rm=482] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 482m
execute @e[tag=track] ~ ~ ~ execute @a[r=484,rm=483] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 483m
execute @e[tag=track] ~ ~ ~ execute @a[r=485,rm=484] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 484m
execute @e[tag=track] ~ ~ ~ execute @a[r=486,rm=485] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 485m
execute @e[tag=track] ~ ~ ~ execute @a[r=487,rm=486] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 486m
execute @e[tag=track] ~ ~ ~ execute @a[r=488,rm=487] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 487m
execute @e[tag=track] ~ ~ ~ execute @a[r=489,rm=488] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 488m
execute @e[tag=track] ~ ~ ~ execute @a[r=490,rm=489] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 489m
execute @e[tag=track] ~ ~ ~ execute @a[r=491,rm=490] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 490m
execute @e[tag=track] ~ ~ ~ execute @a[r=492,rm=491] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 491m
execute @e[tag=track] ~ ~ ~ execute @a[r=493,rm=492] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 492m
execute @e[tag=track] ~ ~ ~ execute @a[r=494,rm=493] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 493m
execute @e[tag=track] ~ ~ ~ execute @a[r=495,rm=494] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 494m
execute @e[tag=track] ~ ~ ~ execute @a[r=496,rm=495] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 495m
execute @e[tag=track] ~ ~ ~ execute @a[r=497,rm=496] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 496m
execute @e[tag=track] ~ ~ ~ execute @a[r=498,rm=497] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 497m
execute @e[tag=track] ~ ~ ~ execute @a[r=499,rm=498] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 498m
execute @e[tag=track] ~ ~ ~ execute @a[r=500,rm=499] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 499m
execute @e[tag=track] ~ ~ ~ execute @a[r=501,rm=500] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 500m
execute @e[tag=track] ~ ~ ~ execute @a[r=502,rm=501] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 501m
execute @e[tag=track] ~ ~ ~ execute @a[r=503,rm=502] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 502m
execute @e[tag=track] ~ ~ ~ execute @a[r=504,rm=503] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 503m
execute @e[tag=track] ~ ~ ~ execute @a[r=505,rm=504] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 504m
execute @e[tag=track] ~ ~ ~ execute @a[r=506,rm=505] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 505m
execute @e[tag=track] ~ ~ ~ execute @a[r=507,rm=506] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 506m
execute @e[tag=track] ~ ~ ~ execute @a[r=508,rm=507] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 507m
execute @e[tag=track] ~ ~ ~ execute @a[r=509,rm=508] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 508m
execute @e[tag=track] ~ ~ ~ execute @a[r=510,rm=509] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 509m
execute @e[tag=track] ~ ~ ~ execute @a[r=511,rm=510] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 510m
execute @e[tag=track] ~ ~ ~ execute @a[r=512,rm=511] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 511m
execute @e[tag=track] ~ ~ ~ execute @a[r=513,rm=512] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 512m