execute @e[tag=track] ~ ~ ~ execute @a[r=770,rm=769] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 769m
execute @e[tag=track] ~ ~ ~ execute @a[r=771,rm=770] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 770m
execute @e[tag=track] ~ ~ ~ execute @a[r=772,rm=771] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 771m
execute @e[tag=track] ~ ~ ~ execute @a[r=773,rm=772] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 772m
execute @e[tag=track] ~ ~ ~ execute @a[r=774,rm=773] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 773m
execute @e[tag=track] ~ ~ ~ execute @a[r=775,rm=774] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 774m
execute @e[tag=track] ~ ~ ~ execute @a[r=776,rm=775] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 775m
execute @e[tag=track] ~ ~ ~ execute @a[r=777,rm=776] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 776m
execute @e[tag=track] ~ ~ ~ execute @a[r=778,rm=777] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 777m
execute @e[tag=track] ~ ~ ~ execute @a[r=779,rm=778] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 778m
execute @e[tag=track] ~ ~ ~ execute @a[r=780,rm=779] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 779m
execute @e[tag=track] ~ ~ ~ execute @a[r=781,rm=780] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 780m
execute @e[tag=track] ~ ~ ~ execute @a[r=782,rm=781] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 781m
execute @e[tag=track] ~ ~ ~ execute @a[r=783,rm=782] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 782m
execute @e[tag=track] ~ ~ ~ execute @a[r=784,rm=783] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 783m
execute @e[tag=track] ~ ~ ~ execute @a[r=785,rm=784] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 784m
execute @e[tag=track] ~ ~ ~ execute @a[r=786,rm=785] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 785m
execute @e[tag=track] ~ ~ ~ execute @a[r=787,rm=786] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 786m
execute @e[tag=track] ~ ~ ~ execute @a[r=788,rm=787] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 787m
execute @e[tag=track] ~ ~ ~ execute @a[r=789,rm=788] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 788m
execute @e[tag=track] ~ ~ ~ execute @a[r=790,rm=789] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 789m
execute @e[tag=track] ~ ~ ~ execute @a[r=791,rm=790] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 790m
execute @e[tag=track] ~ ~ ~ execute @a[r=792,rm=791] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 791m
execute @e[tag=track] ~ ~ ~ execute @a[r=793,rm=792] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 792m
execute @e[tag=track] ~ ~ ~ execute @a[r=794,rm=793] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 793m
execute @e[tag=track] ~ ~ ~ execute @a[r=795,rm=794] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 794m
execute @e[tag=track] ~ ~ ~ execute @a[r=796,rm=795] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 795m
execute @e[tag=track] ~ ~ ~ execute @a[r=797,rm=796] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 796m
execute @e[tag=track] ~ ~ ~ execute @a[r=798,rm=797] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 797m
execute @e[tag=track] ~ ~ ~ execute @a[r=799,rm=798] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 798m
execute @e[tag=track] ~ ~ ~ execute @a[r=800,rm=799] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 799m
execute @e[tag=track] ~ ~ ~ execute @a[r=801,rm=800] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 800m
execute @e[tag=track] ~ ~ ~ execute @a[r=802,rm=801] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 801m
execute @e[tag=track] ~ ~ ~ execute @a[r=803,rm=802] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 802m
execute @e[tag=track] ~ ~ ~ execute @a[r=804,rm=803] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 803m
execute @e[tag=track] ~ ~ ~ execute @a[r=805,rm=804] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 804m
execute @e[tag=track] ~ ~ ~ execute @a[r=806,rm=805] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 805m
execute @e[tag=track] ~ ~ ~ execute @a[r=807,rm=806] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 806m
execute @e[tag=track] ~ ~ ~ execute @a[r=808,rm=807] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 807m
execute @e[tag=track] ~ ~ ~ execute @a[r=809,rm=808] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 808m
execute @e[tag=track] ~ ~ ~ execute @a[r=810,rm=809] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 809m
execute @e[tag=track] ~ ~ ~ execute @a[r=811,rm=810] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 810m
execute @e[tag=track] ~ ~ ~ execute @a[r=812,rm=811] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 811m
execute @e[tag=track] ~ ~ ~ execute @a[r=813,rm=812] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 812m
execute @e[tag=track] ~ ~ ~ execute @a[r=814,rm=813] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 813m
execute @e[tag=track] ~ ~ ~ execute @a[r=815,rm=814] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 814m
execute @e[tag=track] ~ ~ ~ execute @a[r=816,rm=815] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 815m
execute @e[tag=track] ~ ~ ~ execute @a[r=817,rm=816] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 816m
execute @e[tag=track] ~ ~ ~ execute @a[r=818,rm=817] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 817m
execute @e[tag=track] ~ ~ ~ execute @a[r=819,rm=818] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 818m
execute @e[tag=track] ~ ~ ~ execute @a[r=820,rm=819] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 819m
execute @e[tag=track] ~ ~ ~ execute @a[r=821,rm=820] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 820m
execute @e[tag=track] ~ ~ ~ execute @a[r=822,rm=821] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 821m
execute @e[tag=track] ~ ~ ~ execute @a[r=823,rm=822] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 822m
execute @e[tag=track] ~ ~ ~ execute @a[r=824,rm=823] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 823m
execute @e[tag=track] ~ ~ ~ execute @a[r=825,rm=824] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 824m
execute @e[tag=track] ~ ~ ~ execute @a[r=826,rm=825] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 825m
execute @e[tag=track] ~ ~ ~ execute @a[r=827,rm=826] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 826m
execute @e[tag=track] ~ ~ ~ execute @a[r=828,rm=827] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 827m
execute @e[tag=track] ~ ~ ~ execute @a[r=829,rm=828] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 828m
execute @e[tag=track] ~ ~ ~ execute @a[r=830,rm=829] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 829m
execute @e[tag=track] ~ ~ ~ execute @a[r=831,rm=830] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 830m
execute @e[tag=track] ~ ~ ~ execute @a[r=832,rm=831] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 831m
execute @e[tag=track] ~ ~ ~ execute @a[r=833,rm=832] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 832m