
execute @e[tag=track] ~ ~ ~ execute @a[r=962,rm=961] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 961m
execute @e[tag=track] ~ ~ ~ execute @a[r=963,rm=962] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 962m
execute @e[tag=track] ~ ~ ~ execute @a[r=964,rm=963] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 963m
execute @e[tag=track] ~ ~ ~ execute @a[r=965,rm=964] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 964m
execute @e[tag=track] ~ ~ ~ execute @a[r=966,rm=965] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 965m
execute @e[tag=track] ~ ~ ~ execute @a[r=967,rm=966] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 966m
execute @e[tag=track] ~ ~ ~ execute @a[r=968,rm=967] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 967m
execute @e[tag=track] ~ ~ ~ execute @a[r=969,rm=968] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 968m
execute @e[tag=track] ~ ~ ~ execute @a[r=970,rm=969] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 969m
execute @e[tag=track] ~ ~ ~ execute @a[r=971,rm=970] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 970m
execute @e[tag=track] ~ ~ ~ execute @a[r=972,rm=971] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 971m
execute @e[tag=track] ~ ~ ~ execute @a[r=973,rm=972] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 972m
execute @e[tag=track] ~ ~ ~ execute @a[r=974,rm=973] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 973m
execute @e[tag=track] ~ ~ ~ execute @a[r=975,rm=974] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 974m
execute @e[tag=track] ~ ~ ~ execute @a[r=976,rm=975] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 975m
execute @e[tag=track] ~ ~ ~ execute @a[r=977,rm=976] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 976m
execute @e[tag=track] ~ ~ ~ execute @a[r=978,rm=977] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 977m
execute @e[tag=track] ~ ~ ~ execute @a[r=979,rm=978] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 978m
execute @e[tag=track] ~ ~ ~ execute @a[r=980,rm=979] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 979m
execute @e[tag=track] ~ ~ ~ execute @a[r=981,rm=980] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 980m
execute @e[tag=track] ~ ~ ~ execute @a[r=982,rm=981] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 981m
execute @e[tag=track] ~ ~ ~ execute @a[r=983,rm=982] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 982m
execute @e[tag=track] ~ ~ ~ execute @a[r=984,rm=983] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 983m
execute @e[tag=track] ~ ~ ~ execute @a[r=985,rm=984] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 984m
execute @e[tag=track] ~ ~ ~ execute @a[r=986,rm=985] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 985m
execute @e[tag=track] ~ ~ ~ execute @a[r=987,rm=986] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 986m
execute @e[tag=track] ~ ~ ~ execute @a[r=988,rm=987] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 987m
execute @e[tag=track] ~ ~ ~ execute @a[r=989,rm=988] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 988m
execute @e[tag=track] ~ ~ ~ execute @a[r=990,rm=989] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 989m
execute @e[tag=track] ~ ~ ~ execute @a[r=991,rm=990] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 990m
execute @e[tag=track] ~ ~ ~ execute @a[r=992,rm=991] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 991m
execute @e[tag=track] ~ ~ ~ execute @a[r=993,rm=992] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 992m
execute @e[tag=track] ~ ~ ~ execute @a[r=994,rm=993] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 993m
execute @e[tag=track] ~ ~ ~ execute @a[r=995,rm=994] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 994m
execute @e[tag=track] ~ ~ ~ execute @a[r=996,rm=995] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 995m
execute @e[tag=track] ~ ~ ~ execute @a[r=997,rm=996] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 996m
execute @e[tag=track] ~ ~ ~ execute @a[r=998,rm=997] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 997m
execute @e[tag=track] ~ ~ ~ execute @a[r=999,rm=998] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 998m
execute @e[tag=track] ~ ~ ~ execute @a[r=1000,rm=999] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 999m
execute @e[tag=track] ~ ~ ~ execute @a[r=1001,rm=1000] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1000m
execute @e[tag=track] ~ ~ ~ execute @a[r=1002,rm=1001] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1001m
execute @e[tag=track] ~ ~ ~ execute @a[r=1003,rm=1002] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1002m
execute @e[tag=track] ~ ~ ~ execute @a[r=1004,rm=1003] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1003m
execute @e[tag=track] ~ ~ ~ execute @a[r=1005,rm=1004] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1004m
execute @e[tag=track] ~ ~ ~ execute @a[r=1006,rm=1005] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1005m
execute @e[tag=track] ~ ~ ~ execute @a[r=1007,rm=1006] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1006m
execute @e[tag=track] ~ ~ ~ execute @a[r=1008,rm=1007] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1007m
execute @e[tag=track] ~ ~ ~ execute @a[r=1009,rm=1008] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1008m
execute @e[tag=track] ~ ~ ~ execute @a[r=1010,rm=1009] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1009m
execute @e[tag=track] ~ ~ ~ execute @a[r=1011,rm=1010] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1010m
execute @e[tag=track] ~ ~ ~ execute @a[r=1012,rm=1011] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1011m
execute @e[tag=track] ~ ~ ~ execute @a[r=1013,rm=1012] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1012m
execute @e[tag=track] ~ ~ ~ execute @a[r=1014,rm=1013] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1013m
execute @e[tag=track] ~ ~ ~ execute @a[r=1015,rm=1014] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1014m
execute @e[tag=track] ~ ~ ~ execute @a[r=1016,rm=1015] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1015m
execute @e[tag=track] ~ ~ ~ execute @a[r=1017,rm=1016] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1016m
execute @e[tag=track] ~ ~ ~ execute @a[r=1018,rm=1017] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1017m
execute @e[tag=track] ~ ~ ~ execute @a[r=1019,rm=1018] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1018m
execute @e[tag=track] ~ ~ ~ execute @a[r=1020,rm=1019] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1019m
execute @e[tag=track] ~ ~ ~ execute @a[r=1021,rm=1020] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1020m
execute @e[tag=track] ~ ~ ~ execute @a[r=1022,rm=1021] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1021m
execute @e[tag=track] ~ ~ ~ execute @a[r=1023,rm=1022] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1022m
execute @e[tag=track] ~ ~ ~ execute @a[r=1024,rm=1023] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1023m
execute @e[tag=track] ~ ~ ~ execute @a[r=1025,rm=1024] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 1024m