#function detecting 5-8 chunks / 65-128 blocks radius
execute @e[tag=track] ~ ~ ~ execute @a[r=66,rm=65] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 65m
execute @e[tag=track] ~ ~ ~ execute @a[r=67,rm=66] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 66m
execute @e[tag=track] ~ ~ ~ execute @a[r=68,rm=67] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 67m
execute @e[tag=track] ~ ~ ~ execute @a[r=69,rm=68] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 68m
execute @e[tag=track] ~ ~ ~ execute @a[r=70,rm=69] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 69m
execute @e[tag=track] ~ ~ ~ execute @a[r=71,rm=70] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 70m
execute @e[tag=track] ~ ~ ~ execute @a[r=72,rm=71] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 71m
execute @e[tag=track] ~ ~ ~ execute @a[r=73,rm=72] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 72m
execute @e[tag=track] ~ ~ ~ execute @a[r=74,rm=73] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 73m
execute @e[tag=track] ~ ~ ~ execute @a[r=75,rm=74] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 74m
execute @e[tag=track] ~ ~ ~ execute @a[r=76,rm=75] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 75m
execute @e[tag=track] ~ ~ ~ execute @a[r=77,rm=76] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 76m
execute @e[tag=track] ~ ~ ~ execute @a[r=78,rm=77] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 77m
execute @e[tag=track] ~ ~ ~ execute @a[r=79,rm=78] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 78m
execute @e[tag=track] ~ ~ ~ execute @a[r=80,rm=79] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 79m
execute @e[tag=track] ~ ~ ~ execute @a[r=81,rm=80] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 80m
execute @e[tag=track] ~ ~ ~ execute @a[r=82,rm=81] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 81m
execute @e[tag=track] ~ ~ ~ execute @a[r=83,rm=82] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 82m
execute @e[tag=track] ~ ~ ~ execute @a[r=84,rm=83] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 83m
execute @e[tag=track] ~ ~ ~ execute @a[r=85,rm=84] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 84m
execute @e[tag=track] ~ ~ ~ execute @a[r=86,rm=85] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 85m
execute @e[tag=track] ~ ~ ~ execute @a[r=87,rm=86] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 86m
execute @e[tag=track] ~ ~ ~ execute @a[r=88,rm=87] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 87m
execute @e[tag=track] ~ ~ ~ execute @a[r=89,rm=88] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 88m
execute @e[tag=track] ~ ~ ~ execute @a[r=90,rm=89] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 89m
execute @e[tag=track] ~ ~ ~ execute @a[r=91,rm=90] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 90m
execute @e[tag=track] ~ ~ ~ execute @a[r=92,rm=91] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 91m
execute @e[tag=track] ~ ~ ~ execute @a[r=93,rm=92] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 92m
execute @e[tag=track] ~ ~ ~ execute @a[r=94,rm=93] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 93m
execute @e[tag=track] ~ ~ ~ execute @a[r=95,rm=94] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 94m
execute @e[tag=track] ~ ~ ~ execute @a[r=96,rm=95] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 95m
execute @e[tag=track] ~ ~ ~ execute @a[r=97,rm=96] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 96m
execute @e[tag=track] ~ ~ ~ execute @a[r=98,rm=97] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 97m
execute @e[tag=track] ~ ~ ~ execute @a[r=99,rm=98] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 98m
execute @e[tag=track] ~ ~ ~ execute @a[r=100,rm=99] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 99m
execute @e[tag=track] ~ ~ ~ execute @a[r=101,rm=100] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 100m
execute @e[tag=track] ~ ~ ~ execute @a[r=102,rm=101] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 101m
execute @e[tag=track] ~ ~ ~ execute @a[r=103,rm=102] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 102m
execute @e[tag=track] ~ ~ ~ execute @a[r=104,rm=103] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 103m
execute @e[tag=track] ~ ~ ~ execute @a[r=105,rm=104] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 104m
execute @e[tag=track] ~ ~ ~ execute @a[r=106,rm=105] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 105m
execute @e[tag=track] ~ ~ ~ execute @a[r=107,rm=106] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 106m
execute @e[tag=track] ~ ~ ~ execute @a[r=108,rm=107] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 107m
execute @e[tag=track] ~ ~ ~ execute @a[r=109,rm=108] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 108m
execute @e[tag=track] ~ ~ ~ execute @a[r=110,rm=109] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 109m
execute @e[tag=track] ~ ~ ~ execute @a[r=111,rm=110] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 110m
execute @e[tag=track] ~ ~ ~ execute @a[r=112,rm=111] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 111m
execute @e[tag=track] ~ ~ ~ execute @a[r=113,rm=112] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 112m
execute @e[tag=track] ~ ~ ~ execute @a[r=114,rm=113] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 113m
execute @e[tag=track] ~ ~ ~ execute @a[r=115,rm=114] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 114m
execute @e[tag=track] ~ ~ ~ execute @a[r=116,rm=115] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 115m
execute @e[tag=track] ~ ~ ~ execute @a[r=117,rm=116] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 116m
execute @e[tag=track] ~ ~ ~ execute @a[r=118,rm=117] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 117m
execute @e[tag=track] ~ ~ ~ execute @a[r=119,rm=118] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 118m
execute @e[tag=track] ~ ~ ~ execute @a[r=120,rm=119] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 119m
execute @e[tag=track] ~ ~ ~ execute @a[r=121,rm=120] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 120m
execute @e[tag=track] ~ ~ ~ execute @a[r=122,rm=121] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 121m
execute @e[tag=track] ~ ~ ~ execute @a[r=123,rm=122] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 122m
execute @e[tag=track] ~ ~ ~ execute @a[r=124,rm=123] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 123m
execute @e[tag=track] ~ ~ ~ execute @a[r=125,rm=124] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 124m
execute @e[tag=track] ~ ~ ~ execute @a[r=126,rm=125] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 125m
execute @e[tag=track] ~ ~ ~ execute @a[r=127,rm=126] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 126m
execute @e[tag=track] ~ ~ ~ execute @a[r=128,rm=127] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 127m
execute @e[tag=track] ~ ~ ~ execute @a[r=129,rm=128] ~ ~ ~ title @s[tag=!track] actionbar §b§lTracking: @e[tag=track] | Distance: 128m